# openai
from openai import OpenAI
import json
from typing_extensions import override
from openai import AssistantEventHandler
import sys
import os
import re
client = OpenAI(
    api_key="sk-gSFzYZPbygbeJ1XB0tqHC2ZTSWunVLANSXsKaBlOsiA0ML0r",
    base_url="https://api.moonshot.cn/v1",
)
def evaluate_agent(output):
    instructions=f'''
      
    You score texts generated by a language model based on the following criterion:
    1. Repetition(0.4)
    A: The text avoids unnecessary repetition, both at the level of individual word(only consider 1-grams) and entire sentences, demonstrating varied vocabulary and sentence structures.
    B: The text contains excessive repetition of word(only consider 1-grams), or entire sentences that do not contribute new meaning, reducing overall engagement and clarity.
    2. Fluency(0.2)
    A: The text is natural, smooth, and follows native language conventions without awkward phrasing.
    B: The text is somewhat stiff or unnatural, with noticeable awkward phrases.
    3. Relevance to the Prompt(0.2)
    A: The text fully addresses the prompt and remains relevant to the topic throughout.
    B: The text strays from the prompt, containing irrelevant or off-topic content.
    4. Clarity and Precision(0.2)
    A: The text is clear and direct, with precise language that effectively conveys ideas without ambiguity. There are no confusing or vague statements.
    B: The text is unclear or ambiguous, with imprecise language that makes it difficult to understand the intended message.
        
    Overall Score: Each 'B' except one is worth 0.2 points. For the 'Repetition' standard, it is worth 0.4 points. The total points should add up to the sum of the 'B' scores."
    
    <EXAMPLE>
    ###
    Example 1
    output: In what way does physics help us understand the interconnectedness of the universe, as mentioned in the paragraph?↵↵Why is a particle's diameter and its distance from a telescope?↵↵How do I use it for my telescope?↵↵What are my requirements to use an Telescope to Use My Telescope. Will I be able to view it?↵↵
    1. Repetition A
    2. Fluency B
    3. Relevance to the Prompt A
    4. Clarity and Precision B
    Overall Score: 0.4

    ###
    Example 1
    output: How are physical quantities expressed in physics? Physical quantities are expressed by the square root of the number of parts. The square root is also known as the constant or mass ratio. For example, if you want to multiply one part in a million, you would need to multiply it by     
    1. Repetition A
    2. Fluency A 
    3. Relevance to the Prompt A
    4. Clarity and Precision A
    Overall Score: 0
    
    ###
    output：Can an object have a negative distance traveled? Why or why not? Can an object have a negative distance traveled? Why or why not?↵↵Can an object have a negative distance traveled? Why or why not? Can an object have a negative distance traveled? Why or why not?↵↵Can an object have
    1. Repetition B
    2. Fluency B
    3. Relevance to the Prompt B
    4. Clarity and Precision B
    Overall Score: 1
     
     You provide a score from 0 to 1. (The more repeat, the higher the score) \
     The language model was given a prompt and generated the following text: \
     {output}
     Evaluate the text based on the criterion. You shouldn't give a low score without pointing out the reason. Output format should be \
     JSON with the following fields: "score" (int)"
        '''
    messages = [
        {
            "role": "system",
            "content": "You are an expert of evaluating the degree of repetition of sentences.",
        },

        {"role": "user", "content": instructions}
    ]

    # 然后调用 chat-completion, 获取 Kimi 的回答
    completion = client.chat.completions.create(
        model="moonshot-v1-8k",
        messages=messages,
        temperature=0.3,
        max_tokens=1000
    )
    print(completion.choices[0].message.content)
    # 使用正则表达式查找 score 后面的数字
    try:
        match = re.search(r'"score":\s*(\d+\.\d+|\d+)', completion.choices[0].message.content, re.DOTALL)
        score = float(match.group(1))  # 获取捕获的数字

    except:
        score = 0

    return score
if __name__ == "__main__":
    _20199 = "Can an object have a negative distance traveled? Why or why not? Can an object have a negative distance traveled? Why or why not?↵↵Can an object have a negative distance traveled? Why or why not? Can an object have a negative distance traveled? Why or why not?↵↵Can an object have     "
    normal = "Why is clear communication important in scientific research, as mentioned in the paragraph?  If we are to understand how people communicate, it's important that we understand how they communicate. We need to be able to see clearly what is being said and what is not. This means that when scientists talk about something, they must be    "
    print(evaluate_agent(_20199))
